on:
  push:
    branches:
      - "master"
  pull_request:

name: "Build documentation"

jobs:
  build-doc:
    name: "Build documentation"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Setup stable toolchain"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true

      - name: "Build docs"
        run: |
          RUSTDOCFLAGS="-D warnings -A rustdoc::missing-crate-level-docs" cargo doc --all
