on:
  push:
    branches:
      - master
  pull_request:

name: Unused deps
jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install udeps
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps --locked

      - name: Run udeps
        uses: actions-rs/cargo@v1
        with:
          command: udeps
